### PR TITLE
Added link of PostgreSQL Roadmap

### PR DESCRIPTION
**Pull request by syedmouaazfarrukh**
Hi Jun,

I came across your repository [Qix](https://github.com/ty4z2008/Qix) and found it to be a valuable resource for PostgreSQL enthusiasts.

While browsing through the PostgreSQL chapter, I noticed that it was missing links to any structured guides such as the famous ["PostgreSQL Roadmap"](https://roadmap.sh/postgresql-dba). I took the initiative to submit a ["Pull Requests"](https://github.com/ty4z2008/Qix/pull/45) adding it in a under resources section.

Thank you for your time and effort in maintaining this valuable resource :)

Best,
Mouaaz

### CODE REVIEW

**Comment by ifond** [comment]
​ I have received your E-mail——Steven Lee

**Comment by Yujianping123** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by JayVae** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，欢迎联系！收到您的邮件后我会第一时间阅读并回复您的。

**Comment by JayVae** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，欢迎联系！收到您的邮件后我会第一时间阅读并回复您的。

**Comment by Yujianping123** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Pull request closed without merging**
