### PR TITLE
Add three repos in dl2

### PR DESCRIPTION
**Pull request by layumi**

### CODE REVIEW

**Comment by ty4z2008** [comment]
@layumi  i'm excited,You are the first friend of add new repos. 

I believe I can work with you to make this project to help more people

Thanks for your commit.

**Comment by layumi** [comment]
Thank you, @ty4z2008 
It's a great collection. My friends are also interested. 
I will ask them to add their codes to your repos later.

**Comment by Chenfeng1271** [comment]
Sorry,I just don't know the work really do,I  study in maching learning and CV,if necessary,I'd like to give you my hand

**Comment by ty4z2008** [comment]
@Chenfeng1271 Welcome to open pull request

**Comment by ty4z2008** [comment]
@layumi You should tell us . "if you want to contribute to an open source project, don't delay"

**Comment by layumi** [comment]
@ty4z2008  
Yes, Sure. What shall I do?

**Comment by ty4z2008** [comment]
@layumi You can recommend some awesome paper

**Comment by layumi** [comment]
https://distill.pub/2017/feature-visualization/
https://github.com/zhunzhong07/Random-Erasing
https://github.com/syfafterzy/SVDNet-for-Pedestrian-Retrieval

**Comment by layumi** [comment]
https://github.com/yunjey/StarGAN

**Comment by ty4z2008** [comment]
@layumi You can submit the content directly to dl2.md. Then open a pull request

**Pull request merged**
